[package]
name = "lets_do"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
image = "0.25.1"
libsql = "0.4.0"
qrcode = "0.14.0"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.120"
tokio = "1.38.0"
